// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfqturxwzxqyonbewxvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcXR1cnh3enhxeW9uYmV3eHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzY3MDMsImV4cCI6MjA2MDMxMjcwM30.AL3LtzLK12XHwzTPaDmR1-q1tSMISmCbHRIQx1cnCzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);